services:


#  rabbitmq_setup:
#    build:
#      context: ./
#      dockerfile: rabbitmq/setup/Dockerfile
#    container_name: rabbitmq_setup
#    env_file:
#      - .env
#    networks:
#      - rabbitmq_net


  scheduler:
    build:
      context: .  # Корень проекта
      dockerfile: scheduler/Dockerfile  # Путь ОТНОСИТЕЛЬНО корня
    container_name: scheduler
    env_file:
      - .env
    networks:
      - rabbitmq_net

#
#  asker:
#    build:
#      context: ./
#      dockerfile: asker/Dockerfile
#    container_name: asker
#    env_file:
#      - .env
#    networks:
#      - rabbitmq_net
#
#
#  responseer:
#    build:
#      context: ./
#      dockerfile: responser/Dockerfile
#    container_name: responser
#    env_file:
#      - .env
#    networks:
#      - rabbitmq_net
#
#
#
#  reactioner:
#    build:
#      context: ./
#      dockerfile: reactioner/Dockerfile
#    container_name: reactioner
#    env_file:
#      - .env
#    networks:
#      - rabbitmq_net


networks:
  rabbitmq_net:
    external: true  # Используем существующую сеть
    name: rabbitmq_net  # Указываем то же имя
